package com.senlacourses.electronicHotelAdministrator.config.security;

import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

public class CustomUsernamePasswordAuthFilter extends UsernamePasswordAuthenticationFilter {
}
